version: '2'
services:
    angular2uaagateway-cassandra:
        container_name: angular2uaagateway-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/Angular2UaaGateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    angular2uaagateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: angular2uaagateway-cassandra-migration
        links:
            - angular2uaagateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
